
# condense the tokens notifications to one message per given seconds
# time in seconds (0 to disable)
condense-spam: 30
# allow players to have negative tokens
negative-tokens: false
# send an update notification on startup and when an admin joins
update-notification: true
# a list of players that are excluded from /tokens top
# not case-sensitive
leaderboard-exclusion:
  - Not_Jaden
# exchange tokens for in-game items or a placeholder
item-exchange:
  # allow players to use the /tokens deposit and /tokens withdraw commands
  enabled: false
  # what item that tokens can be exchanged for
  object: 'DIAMOND'
  # the value of the object - for the default config, one diamond is worth 30 tokens
  # decimals can be used
  value: 30
  # commands to run when giving the object to a player
  # {amount} and {player} can be used
  add-commands: []
  remove-commands: []
  # include the object items in the player's inventory or the object value of the placeholder in the player's balance
  # this will automatically convert the object into tokens if a transaction requires it
  auto-exchange: false
# formatting of large numbers
number-formatting:
  # text before the currency
  prefix: ''
  # text after the currency
  suffix: ''
  # Same as essentialsX config
  # For 1.234,50 use de-DE
  # For 1,234.50 use en-US
  # For 1'234,50 use fr-ch
  format-locale: en-US
  # pattern for currency to be displayed - symbols are only placeholders, if you want to change the symbols, change format-locale
  pattern: '#,###.##'
  use-divisions: true
  # makes the number smaller and adds a suffix ex: 1000 = 1K | 1234 = 1.23K | 5467900 = 5.47M
  divisions:
    # the division and suffix
    1000: K
    1000000: M
    1000000000: B
    1000000000000: T

# MySQL connection - you don't have to change anything if you don't want to use it
# must restart your server for MySQL changes to take effect
database:
  host: localhost
  port: 3306
  database: db
  user: username
  password: pass
  use-ssl: false
  # automatically move data stored locally to the MySQL database when one connects
  migrate-local-data: true
  # automatically try to connect to the database if a connection was lost
  auto-connect: false
  # the id of the server used to get all players on the network
  # this needs to be different for all servers connected to the same database
  # do not use 0
  server-id: 1
# send your server statistics with bstats
send-bstats: true

# you do not need to worry about this
# whether the old NotTokens config has been adapted to this one
has-adapted: false