name: NotTokensPremium
version: ${project.version}
main: me.jadenp.nottokenspremium.NotTokens
api-version: 1.8
authors: [ Not_Jaden ]
description: You get a token, and you get a tokens; you all get tokens
softdepend:
  - PlaceholderAPI
  - Skript
commands:
  token:
    usage: /token
    description: to add and remove tokens
    aliases:
      - tokens
      - nottokens
      - ntokens
permissions:
  nottokens.admin:
    description: Admin commands
    default: op
    children:
      - nottokens.edit
      - nottokens.player
      - nottokens.viewother
  nottokens.edit:
    description: Edit players' tokens
  nottokens.viewother:
    description: View other players' tokens
  nottokens.player:
    description: Player commands
    children:
      - nottokens.top
      - nottokens.transfer
      - nottokens.balance
  nottokens.top:
    description: See who has the most tokens
    default: true
  nottokens.transfer:
    description: Transfer your tokens to another player
    default: true
  nottokens.balance:
    description: Check your token balance
    default: true
