name: NotTokensPremium
version: ${project.version}
main: me.jadenp.nottokenspremium.NotTokens
api-version: 1.8
authors: [ Not_Jaden ]
description: You get a token, and you get a tokens; you all get tokens
softdepend:
  - PlaceholderAPI
commands:
  token:
    usage: /token
    description: to add and remove tokens
    aliases:
      - tokens
      - nottokens
      - ntokens
permissions:
  nottokens.admin:
    description: ability to add and remove tokens
    default: op
  nottokens.top:
    description: see who has the most tokens
    default: true
